- name: Backend Swarm Network
  community.docker.docker_network:
    name: backend
    driver: overlay
    state: present
    attachable: yes

- name: Deploy MYSQL
  community.docker.docker_swarm_service:
    name: mysql
    image: "{{ mysql_image }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    mounts:
      - source: mysql_data
        target: /var/lib/mysql
        type: volume
    networks:
      - name: backend
    publish:
      - published_port: 3306
        target_port: 3306
    replicas: 1
    restart_config:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
